from .activating_user_account import app
from .contacts import app
from .errors import app
from .flash_message_for_user import app
from .forget_password_enter_email import app
from .forget_password_enter_new_password import app
from .index import app
from .log_in_account import app
from .log_out_personal_account import app
from .personal_account import app
from .process_order import app
from .shopping_cart import app
from .terms_of_delivery import app
from .user_registration import app
